spring:
  application:
    name: hibernate-app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/hibernate
    username: thony32
    password: zerovalo
server:
  port: 8081

